/** 
 * Titulo : EJERCICIO2 *
 */
package ejercicio2;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;

/**
 * Mantenimiento de la tabla Articulos
 * @version Version : 1.0 31 de Enero de 2017
 * @author Jose Rafael Ibañez Zarzo
 * @see <a> http://teceinval.com </a>
 */
public class Articulos extends javax.swing.JFrame {

/**
 * Mantenimiento de la tabla Articulos
 */
static public ResultSet r;                      // Contenido Tablas Articulos
/**
 * Contenido ComboBox Nombre Fabricante
 */
static public ResultSet r2;                     // Contenido ComboBox Nombre Fabricante 
/**
 * Recuperar Nombre Fabricante
 */
static public ResultSet r3;                     // Recuperar Nombre Fabricante
/**
 * Recuperar Codigo Fabricante
 */
static public ResultSet r4;                     // Recuperar Codigo Fabricante
static public Connection conexion;
char esNuevo = ' ';                             //Variable comprobacion resgistro Nuevo o Modificado o Baja 

    public Articulos() throws SQLException {
        initComponents();
    // Conexion a la base de datos
       String url = "jdbc:mysql://localhost:3306/bases";
       String user = "root";
       String pass = "";
       conexion = DriverManager.getConnection(url,user, pass);
        
    // Prepara la conexion de la tabla articulos
        Statement s = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select * from articulos";
        r = s.executeQuery(query);
        
    /*  Ya no se utiliza, pues el combobox se rellena de forma separada
        Query articulos + nombre de fabricantes
    String query =
        "select articulos.*, fabricantes.NOMBRE 
        from articulos left join fabricantes
        on FABRICANTE = COD_FABRICANTE";   
    */  
   
    // Saca el primer registro de articulos
        r.first();
        sacaRegistro();
        activarCampos(false, false, false, false, false, false, false, false, false);        
        muestraBotones(true, true, true, true, true, true, true, false, false);
    // Ocultar campos
        ComboNombre.setVisible(false);
        LabelBorrar.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTITULO = new javax.swing.JLabel();
        LabelCOD_ARTICULO = new javax.swing.JLabel();
        LabelARTICULO = new javax.swing.JLabel();
        LabelFABRICANTE = new javax.swing.JLabel();
        LabelPESO = new javax.swing.JLabel();
        LabelCATEGORIA = new javax.swing.JLabel();
        LabelPRECIO_VENTA = new javax.swing.JLabel();
        LabelPRECIO_COSTE = new javax.swing.JLabel();
        LabelEXISTENCIAS = new javax.swing.JLabel();
        cod_articulo = new javax.swing.JTextField();
        articulo = new javax.swing.JTextField();
        fabricante = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        categoria = new javax.swing.JTextField();
        precio_venta = new javax.swing.JTextField();
        precio_coste = new javax.swing.JTextField();
        existencias = new javax.swing.JTextField();
        BotonPrimero = new javax.swing.JButton();
        BotonAnterior = new javax.swing.JButton();
        BotonSiguiente = new javax.swing.JButton();
        BotonUltimo = new javax.swing.JButton();
        BotonNuevo = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonSuprimir = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonAceptar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        nombrefabricante = new javax.swing.JTextField();
        ComboNombre = new javax.swing.JComboBox<>();
        LabelBorrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLICACION : EJERCICIO2 (BASES)");

        LabelTITULO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTITULO.setText("MANTENIMIENTO DE ARTICULOS");

        LabelCOD_ARTICULO.setText("CODIGO");

        LabelARTICULO.setText("ARTICULO");

        LabelFABRICANTE.setText("FABRICANTE");

        LabelPESO.setText("PESO");

        LabelCATEGORIA.setText("CATEGORIA");

        LabelPRECIO_VENTA.setText("PRECIO VENTA");

        LabelPRECIO_COSTE.setText("PRECIO COSTE");

        LabelEXISTENCIAS.setText("EXISTENCIAS");

        cod_articulo.setEditable(false);

        fabricante.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        peso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        precio_venta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        precio_coste.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        existencias.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        BotonPrimero.setText("Primero");
        BotonPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrimeroActionPerformed(evt);
            }
        });

        BotonAnterior.setText("Anterior");
        BotonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnteriorActionPerformed(evt);
            }
        });

        BotonSiguiente.setText("Siguiente");
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });

        BotonUltimo.setText("Ultimo");
        BotonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUltimoActionPerformed(evt);
            }
        });

        BotonNuevo.setForeground(new java.awt.Color(0, 153, 204));
        BotonNuevo.setText("Nuevo");
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });

        BotonModificar.setForeground(new java.awt.Color(255, 153, 51));
        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        BotonSuprimir.setForeground(new java.awt.Color(255, 0, 51));
        BotonSuprimir.setText("Suprimir");
        BotonSuprimir.setToolTipText("");
        BotonSuprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSuprimirActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonAceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonAceptar.setForeground(new java.awt.Color(0, 204, 102));
        BotonAceptar.setText("√");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        BotonCancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonCancelar.setForeground(new java.awt.Color(255, 0, 0));
        BotonCancelar.setText("X");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        ComboNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ComboNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboNombreActionPerformed(evt);
            }
        });

        LabelBorrar.setForeground(new java.awt.Color(204, 0, 51));
        LabelBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBorrar.setText("Borrar Registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalir))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(LabelTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BotonPrimero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonAnterior)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonSiguiente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonUltimo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(BotonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonModificar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BotonSuprimir)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonCancelar)
                                    .addComponent(BotonAceptar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LabelCOD_ARTICULO, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cod_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LabelCATEGORIA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(LabelEXISTENCIAS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(existencias))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(LabelPRECIO_COSTE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(precio_coste))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(LabelPRECIO_VENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(LabelPESO, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(peso))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(LabelFABRICANTE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombrefabricante)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboNombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BotonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCOD_ARTICULO)
                    .addComponent(cod_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelARTICULO)
                    .addComponent(articulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFABRICANTE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombrefabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ComboNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPESO)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCATEGORIA)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPRECIO_VENTA)
                    .addComponent(precio_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPRECIO_COSTE)
                    .addComponent(precio_coste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelEXISTENCIAS)
                    .addComponent(existencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonPrimero)
                    .addComponent(BotonAnterior)
                    .addComponent(BotonSiguiente)
                    .addComponent(BotonUltimo)
                    .addComponent(BotonAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevo)
                    .addComponent(BotonModificar)
                    .addComponent(BotonCancelar)
                    .addComponent(BotonSuprimir))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// #############################################################################
// ##### METODO BOTONES (Primero, Ultimo, Anterior, Siguiente)             #####
// #############################################################################
    private void BotonPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrimeroActionPerformed
    // Presenta en pantalla el primer registro de la tabla
    try {
        r.first();
        sacaRegistro();
    } catch (SQLException ex) {
        Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BotonPrimeroActionPerformed
    private void BotonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUltimoActionPerformed
    // Presenta en pantalla el ultimo registro de la tabla
    try {
        r.last();
        sacaRegistro();
    } catch (SQLException ex) {
        Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BotonUltimoActionPerformed
    private void BotonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnteriorActionPerformed
    // Presenta en pantalla el registro anterior al actual de la tabla
    try {
        if (r.previous()){
            sacaRegistro();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
    }        
    }//GEN-LAST:event_BotonAnteriorActionPerformed
    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
    // Presenta en pantalla el registro siguiente al actual de la tabla
    try {
        if (r.next()){
            sacaRegistro();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BotonSiguienteActionPerformed
    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
    // Finaliza la ventana del mantenimiento
        this.dispose();                             
    /* Tambien sirve para finalizar la ventana
        this.setVisible(false);
    */
    }//GEN-LAST:event_BotonSalirActionPerformed
// #############################################################################
// ##### METODO BOTONES (Nuevo, Modificar, Borrar)                         #####
// #############################################################################
    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
    // NUEVO REGISTRO
        muestraBotones(false, false, false, false, false, false, false, true, true);
        limpiarPantalla();
        // Genera el combo del nombre de fabricante
            comboFabricante();                  
            activarCampos(true, true, true, true, true, true, true, true, true);  
            nombrefabricante.setVisible(false);
            //ComboNombre.setBounds(3, 4, 20, 40);
            ComboNombre.setVisible(true);  
        //Activar el foco
            cod_articulo.requestFocus();
        // Variable control boton Aceptar
            esNuevo = 'N';    
    }//GEN-LAST:event_BotonNuevoActionPerformed
    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
    // MODIFICA REGISTRO
        muestraBotones(false, false, false, false, false, false, false, true, true);
        // Genera el combo del nombre de fabricante
        comboFabricante();
        activarCampos(false, true, true, true, true, true, true, true, true);
        nombrefabricante.setVisible(false);
        ComboNombre.setVisible(true);  
        //Activar el foco
            articulo.requestFocus();
        // Variable control boton Modificar
            esNuevo = 'M';  
    }//GEN-LAST:event_BotonModificarActionPerformed
// #############################################################################
// ##### METODO BOTONES (Aceptar, Cancelar)                                #####
// #############################################################################
    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
    // ACEPTAR LOS DATOS DE LA PANTALLA (ALTA, MODIFICA, BAJA)
    try {
        String VCod_articulo, vArticulo, vFabricante, vPeso, vCategoria, vPrecioventa, vPreciocoste, vExistencias;
        VCod_articulo = cod_articulo.getText();
        vArticulo = articulo.getText();
        String ww = codigoFabricante(ComboNombre.getSelectedItem().toString());  // Recupera Codigo Fabricante
        vFabricante = fabricante.getText();
        vPeso = peso.getText();
        vCategoria = categoria.getText();
        vPrecioventa = precio_venta.getText();
        vPreciocoste = precio_coste.getText();
        vExistencias = existencias.getText();
        // conectar la base de datos
        String url = "jdbc:mysql://localhost:3306/bases";
        String user = "root";
        String pass = "";
        conexion = DriverManager.getConnection(url, user, pass);
        Statement s = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
      
        // Generar la instruccion de borrar
        if (esNuevo == 'B'){
        String BorraRegistro = "DELETE FROM articulos WHERE COD_ARTICULO='" + VCod_articulo + "'";
        int controlBorra = s.executeUpdate(BorraRegistro);
        /* r.refreshRow(); */
        }
        // Generar la instruccion de actualizar        
        if (esNuevo == 'M'){
        String ActualizaRegistro = "update articulos set ARTICULO='" + vArticulo + "', FABRICANTE='" + vFabricante + "', PESO='" + vPeso + "', CATEGORIA='" + vCategoria + "', PRECIO_VENTA='" + vPrecioventa + "', PRECIO_COSTE='" + vPreciocoste + "', EXISTENCIAS='" + vExistencias + "' WHERE COD_ARTICULO='" + VCod_articulo +"'";
        int controlActualiza = s.executeUpdate(ActualizaRegistro);
        r.refreshRow();
        }
        // Generar la instruccion de Nuevo Registro
        if (esNuevo == 'N'){
        String NuevoRegistro = "insert into articulos values ('" + VCod_articulo + "','" + vArticulo + "','" + vFabricante + "','" + vPeso + "','" + vCategoria + "','" + vPrecioventa + "','" + vPreciocoste + "','" + vExistencias + "')";
        int controlNuevo = s.executeUpdate(NuevoRegistro);
        /* r.refreshRow(); */
        }
        // Volver a refrescar la base de datos
        if (esNuevo != 'M'){
        String query = "select * from articulos";   
            r = s.executeQuery(query);
            r.first();
            sacaRegistro();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
    }
        // Volver activar los botones
        muestraBotones(true, true, true, true, true, true, true, false, false);
        activarCampos(false, false, false, false, false, false, false, false, false);
        LabelBorrar.setVisible(false);
        nombrefabricante.setVisible(true);
        ComboNombre.setVisible(false); 
        sacaRegistro();
        // Variable control boton
            esNuevo = ' ';           
    }//GEN-LAST:event_BotonAceptarActionPerformed
    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
    //CANCELAR LOS CAMBIOS DE LA PANTALLA (ALTA, MODIFICA, BAJA)
        muestraBotones(true, true, true, true, true, true, true, false, false);
        try {
            r.first();
            sacaRegistro();
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
        activarCampos(false, false, false, false, false, false, false, false, false);
        LabelBorrar.setVisible(false);
        nombrefabricante.setVisible(true);
        ComboNombre.setVisible(false);  
        // Variable control boton
            esNuevo = ' '; 
    }//GEN-LAST:event_BotonCancelarActionPerformed
    private void BotonSuprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSuprimirActionPerformed
    // BORRA REGISTRO
        muestraBotones(false, false, false, false, false, false, false, true, true);
        activarCampos(false, false, false, false, false, false, false, false, false);
        LabelBorrar.setVisible(true);
        nombrefabricante.setVisible(true);
        ComboNombre.setVisible(false);  
        
// Variable control boton Suprimir
            esNuevo = 'B';
    }//GEN-LAST:event_BotonSuprimirActionPerformed
// #############################################################################
// ##### METODO PRESENTA COMBOBOX PARA EL FABRICANTE                                #####
// #############################################################################
    private void ComboNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboNombreActionPerformed
      fabricante.setText(codigoFabricante((String)ComboNombre.getSelectedItem()));
    }//GEN-LAST:event_ComboNombreActionPerformed
// #############################################################################
// ##### METODO PARA SACAR EL REGISTRO                                     #####
// #############################################################################
    public void sacaRegistro(){
        try {
            cod_articulo.setText(r.getString("COD_ARTICULO"));
            articulo.setText(r.getString("ARTICULO"));
            fabricante.setText(r.getString("FABRICANTE"));
            nombrefabricante.setText(nombreFabricante(r.getInt("FABRICANTE"))); //Recupera Nombre Fabricante
            peso.setText(r.getString("PESO"));
            categoria.setText(r.getString("CATEGORIA"));
            precio_venta.setText(r.getString("PRECIO_VENTA"));
            precio_coste.setText(r.getString("PRECIO_COSTE"));
            existencias.setText(r.getString("EXISTENCIAS"));
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
// #############################################################################
// ##### METODO PARA GENERAR EL COMBO PARA EL NOMBRE DEL FABRICANTE        #####
// #############################################################################
    public void comboFabricante(){
        try{
            Statement s2 = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query2 = "Select * from fabricantes";
            r2 = s2.executeQuery(query2);
            DefaultComboBoxModel value2 = new DefaultComboBoxModel();
            while (r2.next()) {
                value2.addElement(r2.getString("NOMBRE"));
            }
            ComboNombre.setModel(value2);
            ComboNombre.setSelectedItem(nombreFabricante(r.getInt("FABRICANTE")));
            
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
// #############################################################################
// ##### METODO PARA RECUPERAR EL NOMBRE DEL FABRICANTE                    #####
// #############################################################################
/**
 * @param codigo : entero que identifica al fabricante
 * @return nombreFab : cadena con la descripcion del fabricante
 */
    public String nombreFabricante(int codigo){
        String nombreFab = "";
        try {
            Statement s3 = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query3= "select NOMBRE from fabricantes where COD_FABRICANTE=" + codigo;
            r3 = s3.executeQuery(query3);
            r3.first();
            nombreFab = r3.getString("NOMBRE");
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }   
    return nombreFab;
    }
// #############################################################################
// ##### METODO PARA RECUPERAR EL CODIGO DEL FABRICANTE                    #####
// #############################################################################
/**
 * @param nombre : cadena con la descripcion del fabricante
 * @return codFab : entero que identifica al fabricante
 */
    public String codigoFabricante(String nombre){
        String codFab = "";
        try {
            Statement s4 = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query4= "select COD_FABRICANTE from fabricantes where NOMBRE='" + nombre +"'";
            r4 = s4.executeQuery(query4);
            r4.first();
            codFab = r4.getString("COD_FABRICANTE");
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }   
    return codFab;
    }
// #############################################################################
// ##### METODO MOSTRAR U OCULTAR BOTONES DE LA PANTALLA                   #####
// #############################################################################
    public void muestraBotones(boolean Pr, boolean An, boolean Si, boolean Ul, boolean Nu, boolean Mo, boolean Su, boolean Ac, boolean Ca){
        this.BotonPrimero.setVisible(Pr);
        this.BotonAnterior.setVisible(An);
        this.BotonSiguiente.setVisible(Si);
        this.BotonUltimo.setVisible(Ul);
        this.BotonNuevo.setVisible(Nu);
        this.BotonModificar.setVisible(Mo);
        this.BotonSuprimir.setVisible(Su);

        this.BotonAceptar.setVisible(Ac);
        this.BotonCancelar.setVisible(Ca);
    }
// #############################################################################
// ##### METODO ACTIVAR O DESACTIVAR CAMPOS EN PANTALLA                   #####
// #############################################################################
    public void activarCampos(boolean C1, boolean C2, boolean C3, boolean C4, boolean C5, boolean C6, boolean C7, boolean C8, boolean C9){
        cod_articulo.setEditable(C1);
        articulo.setEditable(C2);
        fabricante.setEditable(C3);
        nombrefabricante.setEditable(C4);
        peso.setEditable(C5);
        categoria.setEditable(C6);
        precio_venta.setEditable(C7);
        precio_coste.setEditable(C8);
        existencias.setEditable(C9);
    }
// #############################################################################
// ##### METODO LIMPIAR LOS CAMPOS EN LA PANTALLA                          #####
// #############################################################################
    public void limpiarPantalla(){
        cod_articulo.setText(""); 
        articulo.setText(""); 
        fabricante.setText("");
        nombrefabricante.setText("");
        peso.setText("");
        categoria.setText("");
        precio_venta.setText("");
        precio_coste.setText("");
        existencias.setText("");
    }
// #############################################################################
// ##### METODO MAIN                                                       #####
// #############################################################################
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Articulos().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonAnterior;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonNuevo;
    private javax.swing.JButton BotonPrimero;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JButton BotonSuprimir;
    private javax.swing.JButton BotonUltimo;
    private javax.swing.JComboBox<String> ComboNombre;
    private javax.swing.JLabel LabelARTICULO;
    private javax.swing.JLabel LabelBorrar;
    private javax.swing.JLabel LabelCATEGORIA;
    private javax.swing.JLabel LabelCOD_ARTICULO;
    private javax.swing.JLabel LabelEXISTENCIAS;
    private javax.swing.JLabel LabelFABRICANTE;
    private javax.swing.JLabel LabelPESO;
    private javax.swing.JLabel LabelPRECIO_COSTE;
    private javax.swing.JLabel LabelPRECIO_VENTA;
    private javax.swing.JLabel LabelTITULO;
    private javax.swing.JTextField articulo;
    private javax.swing.JTextField categoria;
    private javax.swing.JTextField cod_articulo;
    private javax.swing.JTextField existencias;
    private javax.swing.JTextField fabricante;
    private javax.swing.JTextField nombrefabricante;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField precio_coste;
    private javax.swing.JTextField precio_venta;
    // End of variables declaration//GEN-END:variables
}
