/** 
 * Titulo : EJERCICIO2 *
 */
package ejercicio2;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;

/**
 * Mantenimiento de la tabla Clientes
 * @version Version : 1.0 31 de Enero de 2017
 * @author Jose Rafael Ibañez Zarzo
 * @see <a> http://teceinval.com </a>
 */
public class Clientes extends javax.swing.JFrame {

/**
 * Mantenimiento de la tabla Clientes
 */
static public ResultSet r;                      // Contenido Tablas Clientes
static public Connection conexion;
char esNuevo = ' ';

    public Clientes() throws SQLException {
        initComponents();
    // Conexion a la base de datos
        String url = "jdbc:mysql://localhost:3306/bases";
        String user = "root";
        String pass = "";
        conexion = DriverManager.getConnection(url,user, pass);
        
    // Prepara la conexion de la tabla clientes
        Statement s = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query = "select * from clientes";
        r = s.executeQuery(query);
    // Saca el primer registro de clientes
        r.first();
        sacaRegistro();
        activarCampos(false, false, false, false, false, false);        
        muestraBotones(true, true, true, true, true, true, true, false, false);
    // Ocultar campos
        LabelBorrar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTITULO = new javax.swing.JLabel();
        LabelNIF = new javax.swing.JLabel();
        LabelNOMBRE = new javax.swing.JLabel();
        LabelDIRECCION = new javax.swing.JLabel();
        LabelPOBLACION = new javax.swing.JLabel();
        LabelPROVINCIA = new javax.swing.JLabel();
        LabelTELEFONO = new javax.swing.JLabel();
        nif = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        poblacion = new javax.swing.JTextField();
        provincia = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        BotonPrimero = new javax.swing.JButton();
        BotonAnterior = new javax.swing.JButton();
        BotonSiguiente = new javax.swing.JButton();
        BotonUltimo = new javax.swing.JButton();
        BotonNuevo = new javax.swing.JButton();
        BotonModificar = new javax.swing.JButton();
        BotonSuprimir = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonAceptar = new javax.swing.JButton();
        BotonCancelar = new javax.swing.JButton();
        LabelBorrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLICACION : EJERCICIO2 (BASES)");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LabelTITULO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTITULO.setText("MANTENIMIENTO DE CLIENTES");

        LabelNIF.setText("NIF");

        LabelNOMBRE.setText("NOMBRE");

        LabelDIRECCION.setText("DIRECCION");

        LabelPOBLACION.setText("POBLACION");

        LabelPROVINCIA.setText("PROVINCIA");

        LabelTELEFONO.setText("TELEFONO");

        nif.setEditable(false);
        nif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nifActionPerformed(evt);
            }
        });

        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });

        telefono.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });

        BotonPrimero.setText("Primero");
        BotonPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrimeroActionPerformed(evt);
            }
        });

        BotonAnterior.setText("Anterior");
        BotonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnteriorActionPerformed(evt);
            }
        });

        BotonSiguiente.setText("Siguiente");
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });

        BotonUltimo.setText("Ultimo");
        BotonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUltimoActionPerformed(evt);
            }
        });

        BotonNuevo.setForeground(new java.awt.Color(0, 153, 204));
        BotonNuevo.setText("Nuevo");
        BotonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoActionPerformed(evt);
            }
        });

        BotonModificar.setForeground(new java.awt.Color(255, 153, 51));
        BotonModificar.setText("Modificar");
        BotonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarActionPerformed(evt);
            }
        });

        BotonSuprimir.setForeground(new java.awt.Color(255, 0, 51));
        BotonSuprimir.setText("Suprimir");
        BotonSuprimir.setToolTipText("");
        BotonSuprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSuprimirActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonAceptar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonAceptar.setForeground(new java.awt.Color(0, 204, 102));
        BotonAceptar.setText("√");
        BotonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAceptarActionPerformed(evt);
            }
        });

        BotonCancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BotonCancelar.setForeground(new java.awt.Color(255, 0, 0));
        BotonCancelar.setText("X");
        BotonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarActionPerformed(evt);
            }
        });

        LabelBorrar.setForeground(new java.awt.Color(204, 0, 51));
        LabelBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBorrar.setText("Borrar Registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(LabelTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonSalir))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonPrimero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonSiguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonUltimo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(BotonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonSuprimir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BotonCancelar)
                                .addGap(2, 2, 2))
                            .addComponent(BotonAceptar, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelDIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelPOBLACION, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelPROVINCIA, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelTELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nif, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BotonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelTITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNIF)
                    .addComponent(nif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNOMBRE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelDIRECCION)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPOBLACION)
                    .addComponent(poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPROVINCIA)
                    .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTELEFONO)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(LabelBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonPrimero)
                    .addComponent(BotonAnterior)
                    .addComponent(BotonSiguiente)
                    .addComponent(BotonUltimo)
                    .addComponent(BotonAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevo)
                    .addComponent(BotonModificar)
                    .addComponent(BotonCancelar)
                    .addComponent(BotonSuprimir))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void nifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nifActionPerformed
// #############################################################################
// ##### METODO BOTONES (Primero, Ultimo, Anterior, Siguiente)             #####
// #############################################################################
    private void BotonPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrimeroActionPerformed
    // Presenta en pantalla el primer registro de la tabla
        try {
        r.first();
        sacaRegistro();
    } catch (SQLException ex) {
        Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BotonPrimeroActionPerformed

    private void BotonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUltimoActionPerformed
    // Presenta en pantalla el ultimo registro de la tabla
    try {
        r.last();
        sacaRegistro();
    } catch (SQLException ex) {
        Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BotonUltimoActionPerformed

    private void BotonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnteriorActionPerformed
    // Presenta en pantalla el registro anterior al actual de la tabla
    try {
        if (r.previous()){
        sacaRegistro();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
    }        
    }//GEN-LAST:event_BotonAnteriorActionPerformed

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
    // Presenta en pantalla el registro siguiente al actual de la tabla
    try {
        if (r.next()){
        sacaRegistro();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_BotonSiguienteActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
    // Finaliza la ventana del mantenimiento
        this.dispose();
    /* Tambien sirve para finalizar la ventana
        this.setVisible(false);
    */
    }//GEN-LAST:event_BotonSalirActionPerformed
// #############################################################################
// ##### METODO BOTONES (Nuevo, Modificar, Borrar)                         #####
// #############################################################################
    private void BotonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoActionPerformed
    // NUEVO REGISTRO
        muestraBotones(false, false, false, false, false, false, false, true, true);
        limpiarPantalla();
        activarCampos(true, true, true, true, true, true);
        //Activar el foco
            nif.requestFocus();  
        // Variable control boton Aceptar
            esNuevo = 'N';    
    }//GEN-LAST:event_BotonNuevoActionPerformed
    private void BotonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarActionPerformed
    // MODIFICA REGISTRO
        muestraBotones(false, false, false, false, false, false, false, true, true);
        activarCampos(false, true, true, true, true, true);
            
        //Activar el foco
            nombre.requestFocus();
        
        // Variable control boton Modificar
            esNuevo = 'M';  
    }//GEN-LAST:event_BotonModificarActionPerformed
// #############################################################################
// ##### METODO BOTONES (Aceptar, Cancelar)                                #####
// #############################################################################
    private void BotonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAceptarActionPerformed
    try {
        String vNif, vNombre, vDireccion, vPoblacion, vProvincia, vTelefono;
        vNif = nif.getText();
        vNombre = nombre.getText();
        vDireccion = direccion.getText();
        vPoblacion = poblacion.getText();
        vProvincia = provincia.getText();
        vTelefono = telefono.getText();
        // conectar la base de datos
        String url = "jdbc:mysql://localhost:3306/bases";
        String user = "root";
        String pass = "";
        conexion = DriverManager.getConnection(url, user, pass);
        Statement s = conexion.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
      
        // Generar la instruccion de borrar
        if (esNuevo == 'B'){
        String BorraRegistro = "DELETE FROM clientes WHERE NIF='" + vNif + "'";
        int controlBorra = s.executeUpdate(BorraRegistro);
        /* r.refreshRow(); */
        }
        // Generar la instruccion de actualizar        
        if (esNuevo == 'M'){
        String ActualizaRegistro = "update clientes set NOMBRE='" + vNombre + "', DIRECCION='" + vDireccion + "', POBLACION='" + vPoblacion + "', PROVINCIA='" + vProvincia + "', TELEFONO='" + vTelefono + "' WHERE NIF='" + vNif +"'";
        int controlActualiza = s.executeUpdate(ActualizaRegistro);
        r.refreshRow();
        }
        // Generar la instruccion de Nuevo Registro
        if (esNuevo == 'N'){
        String NuevoRegistro = "insert into clientes values ('" + vNif + "','" + vNombre + "','" + vDireccion + "','" + vPoblacion + "','" + vProvincia + "','" + vTelefono + "')";
        int controlNuevo = s.executeUpdate(NuevoRegistro);
        /* r.refreshRow(); */
        }
        // Volver a refrescar la base de datos
        if (esNuevo != 'M'){
        String query = "select * from clientes";   
            r = s.executeQuery(query);
            r.first();
            sacaRegistro();
            }
    } catch (SQLException ex) {
        Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
    }
        // Volver activar los botones
        muestraBotones(true, true, true, true, true, true, true, false, false);
        activarCampos(false, false, false, false, false, false);
        LabelBorrar.setVisible(false); 
   
        // Variable control boton
            esNuevo = ' '; 
    }//GEN-LAST:event_BotonAceptarActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarActionPerformed
    //CANCELAR CAMBIOS
        muestraBotones(true, true, true, true, true, true, true, false, false);
        
        try {
            r.first();
            sacaRegistro();
        } catch (SQLException ex) {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        activarCampos(false, false, false, false, false, false);
        LabelBorrar.setVisible(false); 
            
        // Variable control boton
            esNuevo = ' '; 
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void BotonSuprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSuprimirActionPerformed
    // BORRA REGISTRO
        muestraBotones(false, false, false, false, false, false, false, true, true);
        activarCampos(false, false, false, false, false, false);
        LabelBorrar.setVisible(true); 
           
        // Variable control boton suprimir
            esNuevo = 'B';
    }//GEN-LAST:event_BotonSuprimirActionPerformed
// #############################################################################
// ##### METODO PARA SACAR EL REGISTRO                                     #####
// #############################################################################
    public void sacaRegistro(){
        try {
        nif.setText(r.getString("NIF"));
        nombre.setText(r.getString("NOMBRE"));
        direccion.setText(r.getString("DIRECCION"));
        poblacion.setText(r.getString("POBLACION"));
        provincia.setText(r.getString("PROVINCIA"));
        telefono.setText(r.getString("TELEFONO"));
        } catch (SQLException ex) {
            Logger.getLogger(Articulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
// #############################################################################
// ##### METODO MOSTRAR U OCULTAR BOTONES DE LA PANTALLA                   #####
// #############################################################################
    public void muestraBotones(boolean Pr, boolean An, boolean Si, boolean Ul, boolean Nu, boolean Mo, boolean Su, boolean Ac, boolean Ca){
        this.BotonPrimero.setVisible(Pr);
        this.BotonAnterior.setVisible(An);
        this.BotonSiguiente.setVisible(Si);
        this.BotonUltimo.setVisible(Ul);
        this.BotonNuevo.setVisible(Nu);
        this.BotonModificar.setVisible(Mo);
        this.BotonSuprimir.setVisible(Su);

        this.BotonAceptar.setVisible(Ac);
        this.BotonCancelar.setVisible(Ca);
    }
// #############################################################################
// ##### METODO ACTIVAR O DESACTIVAR CAMPOS EN PANTALLA                   #####
// #############################################################################
    public void activarCampos(boolean C1, boolean C2, boolean C3, boolean C4,boolean C5, boolean C6){
        nif.setEditable(C1);
        nombre.setEditable(C2);
        direccion.setEditable(C3);
        poblacion.setEditable(C4);
        provincia.setEditable(C5);
        telefono.setEditable(C6);
    }
// #############################################################################
// ##### METODO LIMPIAR LOS CAMPOS EN LA PANTALLA                          #####
// #############################################################################
    public void limpiarPantalla(){
        nif.setText(""); 
        nombre.setText(""); 
        direccion.setText(""); 
        poblacion.setText("");
        provincia.setText("");
        telefono.setText("");
    }    
// #############################################################################
// ##### METODO MAIN                                                       #####
// #############################################################################
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Clientes().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAceptar;
    private javax.swing.JButton BotonAnterior;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonModificar;
    private javax.swing.JButton BotonNuevo;
    private javax.swing.JButton BotonPrimero;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JButton BotonSuprimir;
    private javax.swing.JButton BotonUltimo;
    private javax.swing.JLabel LabelBorrar;
    private javax.swing.JLabel LabelDIRECCION;
    private javax.swing.JLabel LabelNIF;
    private javax.swing.JLabel LabelNOMBRE;
    private javax.swing.JLabel LabelPOBLACION;
    private javax.swing.JLabel LabelPROVINCIA;
    private javax.swing.JLabel LabelTELEFONO;
    private javax.swing.JLabel LabelTITULO;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField nif;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField poblacion;
    private javax.swing.JTextField provincia;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
